default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PSWD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: tram-pw_devlopment

test:
  <<: *default
  database: tram-pw_test

production:
  <<: *default
  socket: /var/lib/mysql/mysql.sock
  username: <%= ENV['DB_NAME'] %>
  password: <%= ENV['DB_PSWD'] %>
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
