default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tram-pw
  pool: 5
  username: root
  password: seiya0104
  socket: /var/lib/mysql/mysql.sock
  host: mysql-tram-pw.c28kjha8lmgn.ap-northeast-1.rds.amazonaws.com

development:
  <<: *default
  database: tram-pw_devlopment
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: tram-pw_test

production:
  <<: *default
  database: tram-pw_production
